In [41]:
import torch

## Initialize a tensor from an hetegrogenous python list

In [ ]:
rom a list of multiple types

tensor = torch.tensor([
    [1, 1.0, True], 
    [4, 0.004, 5]
])

print("1.", tensor, tensor.shape, tensor.dtype, sep="\n")

1.
tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00],
        [4.0000e+00, 4.0000e-03, 5.0000e+00]])
torch.Size([2, 3])
torch.float32


In [13]:
tensor = torch.tensor([
    True, True
])

print("2.", tensor, tensor.shape, tensor.dtype, sep="\n")

2.
tensor([True, True])
torch.Size([2])
torch.bool


The tensor above is of type `bool` since it contains only booleans.

In [15]:
tensor = torch.tensor([
    1, 2, 3, 4
])

print("3.", tensor, tensor.shape, tensor.dtype, sep="\n")

3.
tensor([1, 2, 3, 4])
torch.Size([4])
torch.int64


## Random tensor

In [17]:
tensor = torch.rand([2, 2])
print("4.", tensor, tensor.shape, tensor.dtype, sep="\n")

4.
tensor([[0.9184, 0.4106],
        [0.9248, 0.0942]])
torch.Size([2, 2])
torch.float32


> Note: The default random tensor datatype is f32

### We can specify a type such a `float64`, but note that the `rand` function can operate only on float values!

In [28]:
tensor = torch.rand(2, 2, 2, dtype=torch.float64)
print("5.", tensor, tensor.shape, tensor.dtype, sep="\n")

5.
tensor([[[0.7679, 0.2599],
         [0.2527, 0.5134]],

        [[0.7385, 0.9283],
         [0.7638, 0.1021]]], dtype=torch.float64)
torch.Size([2, 2, 2])
torch.float64


In [43]:
# Uniformly random Integers 
tensor = torch.randint(0, 10, [2, 2])
print("6.", tensor, tensor.shape, tensor.dtype, sep="\n")

6.
tensor([[5, 6],
        [3, 9]])
torch.Size([2, 2])
torch.int64


In [35]:
# Normal Distrobution
tensor = torch.randn(2, 2, 2)
print("7.", tensor, tensor.shape, tensor.dtype, sep="\n")

7.
tensor([[[ 0.3268,  0.7446],
         [-0.6728, -0.4033]],

        [[-0.8787, -0.5064],
         [ 0.4564, -0.5103]]])
torch.Size([2, 2, 2])
torch.float32


## Part 2, Linalg

In [57]:
# Create multiple N 2x2 matrices
N = 5
tensor = torch.randn([N, 2, 2])
print(tensor, tensor.shape, tensor.dtype, "", sep="\n")

# Compute the eigenvalues of all matrices.
# Notice that the `eigvals` function takes a tensor whose first dimension is the batch, exactly what we have!
eigvals = torch.linalg.eigvals(tensor)
print("Eigenvalues", eigvals, "", sep="\n")

# The frobenius norm is the $\sqrt{\sum{|a_ij|}}$
frobenius = torch.linalg.matrix_norm(tensor, ord="fro")
print("Frobenius Norm", frobenius, "", sep="\n")

# The euclideian norm is the $\sqrt{\sum{|a_ij|^2}}$
euclidean = torch.sqrt((tensor * tensor).sum())
euclidean2 = tensor.norm()
print("Euclidean Norm", euclidean, euclidean2, "", sep="\n")

tensor([[[ 0.6158, -2.0709],
         [ 0.8364, -2.1070]],

        [[ 0.4891,  1.0043],
         [-0.9748,  0.1507]],

        [[ 0.3325,  0.9100],
         [ 0.1926, -0.0610]],

        [[ 0.5734, -0.8583],
         [-0.6984, -1.5655]],

        [[-0.1325, -0.9578],
         [ 1.2367,  0.4571]]])
torch.Size([5, 2, 2])
torch.float32

Eigenvalues
tensor([[-0.3974+0.0000j, -1.0938+0.0000j],
        [ 0.3199+0.9748j,  0.3199-0.9748j],
        [ 0.5983+0.0000j, -0.3268+0.0000j],
        [ 0.8242+0.0000j, -1.8164+0.0000j],
        [ 0.1623+1.0477j,  0.1623-1.0477j]])

Frobenius Norm
tensor([3.1316, 1.4902, 0.9896, 2.0010, 1.6350])

Euclidean Norm
tensor(4.4367)
tensor(4.4367)

