# 22961, Mmn11

Author: Tal Glanzman

## Question 1

In [5]:
import torch

def can_be_expanded(from_size: torch.Size, to_size: torch.Size) -> bool:
    return True

def expand_as(tensor: torch.Tensor, other: torch.Tensor) -> torch.Tensor:
    print("Not implemented")

In [8]:
# Some examples
A = torch.arange(3).reshape(1, 3)
B = torch.arange(9).reshape(3, 3)

C1 = expand_as(A, B)
C2 = A.expand_as(B)

print(A, B, f"Can be expanded: {can_be_expanded(A, B)}", C1, C2, sep="\n")

Not implemented
tensor([[0, 1, 2]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Can be expanded: True
None
tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])


In [95]:
A = torch.ones(3)
B = torch.arange(6).reshape(2, 3)

def can_expand(tensor: torch.Tensor, to_shape: torch.Size) -> bool:
    from_shape = tensor.shape
    if len(from_shape) > len(to_shape):
        return False

    for i in range(len(from_shape)):
        from_dimsize = a_size[len(from_shape) - 1 - i]
        to_dimsize = b_size[len(from_shape) - 1 - i]
        if from_dimsize != to_dimsize and from_dimsize != 1:
            return False
    
    return True

def expand(tensor: torch.Tensor, to_shape: torch.Size) -> torch.Tensor:
    ans = tensor.clone()

    print("Tensor", tuple(tensor.shape))
    print("To", tuple(to_shape))
    
    # Iterate on every (to) dimension
    for i in range(len(to_shape)):

        # A cursor to the current dimension in `to_shape`
        j = len(to_shape) - 1 - i

        # A cursor to the current dimension in `tensor.shape`.
        # Note that it can be negative at first, but at most -1.
        k = len(ans.shape) - 1 - i

        if k < 0:
            # It is sufficient to only add one degenerate dimension because we
            # add them one by one - so we know that the index will be in bounds.
            ans = ans.unsqueeze(0)
            k = 0

        ans_dimsize = ans.shape[k]
        to_dimsize = to_shape[j]

        print(f"i={i}, j={j}, k={k}, td={ans_dimsize}, to={to_dimsize}")

        if ans_dimsize != to_dimsize:
            if ans_dimsize != 1:
                raise Exception(f"Cannot expand tensor with shape {tuple(ans.shape)} to shape {tuple(to_shape)}")
            ans = torch.cat([ans] * to_dimsize, dim=k)
        
    return ans

print("A", A, A.shape)
print("B", B, B.shape)

C = expand(A, B.shape)
print("C", C, C.shape)

A tensor([1., 1., 1.]) torch.Size([3])
B tensor([[0, 1, 2],
        [3, 4, 5]]) torch.Size([2, 3])
Tensor (3,)
To (2, 3)
i=0, j=1, k=0, td=3, to=3
i=1, j=0, k=0, td=1, to=2
C tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3])


In [81]:
A = torch.arange(2).reshape(2, 1)
B = torch.arange(12).reshape(3, 2, 2)

C0 = A.clone()
C1 = torch.cat([C] * 2, dim=1)
C2 = C.unsqueeze(dim=0)
C3 = torch.cat([C] * 3, dim=0)

print("A", A, A.shape, "", sep="\n")
print("B", B, B.shape, "", sep="\n")
print("C0", C0, C0.shape, "", sep="\n")
print("C1", C1, C1.shape, "", sep="\n")
print("C2", C2, C2.shape, "", sep="\n")
print("C3", C3, C3.shape, "", sep="\n")

A
tensor([[0],
        [1]])
torch.Size([2, 1])

B
tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])
torch.Size([3, 2, 2])

C0
tensor([[0],
        [1]])
torch.Size([2, 1])

C1
tensor([[[0, 0],
         [1, 1],
         [0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1],
         [0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1],
         [0, 0],
         [1, 1]]])
torch.Size([3, 4, 2])

C2
tensor([[[[0, 0],
          [1, 1]],

         [[0, 0],
          [1, 1]],

         [[0, 0],
          [1, 1]]]])
torch.Size([1, 3, 2, 2])

C3
tensor([[[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]],

        [[0, 0],
         [1, 1]]])
torch.Size([9, 2, 2])

